# Taller 2b
### Nombre: David Alejandro Díaz Pineda

Haga modificaciones a las funciones base del siguiente código:
https://github.com/ztjona/MN-prueba-02/tree/main



In [62]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [63]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-13 19:31:16][INFO] 2026-01-13 19:31:16.426199


In [64]:
%autoreload 2
from src import eliminacion_gaussiana


In [65]:
import numpy as np


# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

        print(f"\n{A}")
    # # --- Sustitución hacia atrás
    # solucion = np.zeros(n)
    # solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    # for i in range(n - 2, -1, -1):
    #     suma = 0
    #     for j in range(i + 1, n):
    #         suma += A[i, j] * solucion[j]
    #     solucion[i] = (A[i, n] - suma) / A[i, i]

    return A

In [66]:
def matriz_inversa(A: np.ndarray) -> np.ndarray:
    """Calcula la matriz inversa de A usando eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz cuadrada a invertir.

    ## Return

    ``A_inv``: matriz inversa de A.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)

    n = A.shape[0]
   
    A_aumentada = np.hstack((A, np.eye(n)))

    A_reducida = gauss_jordan(A_aumentada)

    A_inversa = A_reducida[:, n:]

    return A_inversa    

## 1) Para encontrar la matriz inversa de las siguientes matrices:

$$
\begin{bmatrix}
1 & 3 & 4 \\
2 & 1 & 3 \\
4 & 2 & 1
\end{bmatrix}
$$


In [67]:
A1=[[1,3,4],
   [2,1,3],
   [4,2,1]
   ]

In [68]:
matriz_inversa(np.array(A1))

[01-13 19:31:16][INFO] 
[[  1.   3.   4.   1.   0.   0.]
 [  0.  -5.  -5.  -2.   1.   0.]
 [  0. -10. -15.  -4.   0.   1.]]
[01-13 19:31:16][INFO] 
[[ 1.   0.   1.  -0.2  0.6  0. ]
 [-0.   1.   1.   0.4 -0.2 -0. ]
 [ 0.   0.  -5.   0.  -2.   1. ]]
[01-13 19:31:16][INFO] 
[[ 1.   0.   0.  -0.2  0.2  0.2]
 [-0.   1.   0.   0.4 -0.6  0.2]
 [-0.  -0.   1.  -0.   0.4 -0.2]]


array([[-0.2,  0.2,  0.2],
       [ 0.4, -0.6,  0.2],
       [-0. ,  0.4, -0.2]])

$$
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & 4 \\
5 & 6 & 0
\end{bmatrix}
$$

In [69]:
A2 = [[1,2,3],
      [0,1,4],
      [5,6,0]]

In [70]:
matriz_inversa(np.array(A2))

[01-13 19:31:17][INFO] 
[[  1.   2.   3.   1.   0.   0.]
 [  0.   1.   4.   0.   1.   0.]
 [  0.  -4. -15.  -5.   0.   1.]]
[01-13 19:31:17][INFO] 
[[ 1.  0. -5.  1. -2.  0.]
 [ 0.  1.  4.  0.  1.  0.]
 [ 0.  0.  1. -5.  4.  1.]]
[01-13 19:31:17][INFO] 
[[  1.   0.   0. -24.  18.   5.]
 [  0.   1.   0.  20. -15.  -4.]
 [  0.   0.   1.  -5.   4.   1.]]


array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

$$
\begin{bmatrix}
4 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 4
\end{bmatrix}
$$

In [71]:
A3= [[4,2,1],
     [2,1,3],
     [1,3,4]
    ]

In [72]:
matriz_inversa(np.array(A3))

[01-13 19:31:17][INFO] 
[[  1.   3.   4.   0.   0.   1.]
 [  0.  -5.  -5.   0.   1.  -2.]
 [  0. -10. -15.   1.   0.  -4.]]
[01-13 19:31:17][INFO] 
[[ 1.   0.   1.   0.   0.6 -0.2]
 [-0.   1.   1.  -0.  -0.2  0.4]
 [ 0.   0.  -5.   1.  -2.   0. ]]
[01-13 19:31:17][INFO] 
[[ 1.   0.   0.   0.2  0.2 -0.2]
 [-0.   1.   0.   0.2 -0.6  0.4]
 [-0.  -0.   1.  -0.2  0.4 -0. ]]


array([[ 0.2,  0.2, -0.2],
       [ 0.2, -0.6,  0.4],
       [-0.2,  0.4, -0. ]])

$$
\begin{bmatrix}
2 & 4 & 6 & 1 \\
4 & 7 & 5 & -6 \\
2 & 5 & 18 & 10 \\
6 & 12 & 38 & 16
\end{bmatrix}
$$

In [73]:
A4 = [[2,4,6,1],
      [4,7,5,-6],
      [2,5,18,10],
      [6,12,38,16]]

In [74]:
matriz_inversa(np.array(A4))

[01-13 19:31:17][INFO] 
[[ 1.   2.   3.   0.5  0.5  0.   0.   0. ]
 [ 0.  -1.  -7.  -8.  -2.   1.   0.   0. ]
 [ 0.   1.  12.   9.  -1.   0.   1.   0. ]
 [ 0.   0.  20.  13.  -3.   0.   0.   1. ]]
[01-13 19:31:17][INFO] 
[[  1.    0.  -11.  -15.5  -3.5   2.    0.    0. ]
 [ -0.    1.    7.    8.    2.   -1.   -0.   -0. ]
 [  0.    0.    5.    1.   -3.    1.    1.    0. ]
 [  0.    0.   20.   13.   -3.    0.    0.    1. ]]
[01-13 19:31:17][INFO] 
[[  1.    0.    0.  -13.3 -10.1   4.2   2.2   0. ]
 [ -0.    1.    0.    6.6   6.2  -2.4  -1.4  -0. ]
 [  0.    0.    1.    0.2  -0.6   0.2   0.2   0. ]
 [  0.    0.    0.    9.    9.   -4.   -4.    1. ]]
[01-13 19:31:17][INFO] 
[[ 1.          0.          0.          0.          3.2        -1.71111111
  -3.71111111  1.47777778]
 [-0.          1.          0.          0.         -0.4         0.53333333
   1.53333333 -0.73333333]
 [ 0.          0.          1.          0.         -0.8         0.28888889
   0.28888889 -0.02222222]
 [ 0.          0. 

array([[ 3.2       , -1.71111111, -3.71111111,  1.47777778],
       [-0.4       ,  0.53333333,  1.53333333, -0.73333333],
       [-0.8       ,  0.28888889,  0.28888889, -0.02222222],
       [ 1.        , -0.44444444, -0.44444444,  0.11111111]])

## 2) Calcule la descomposición LU para estas matrices y encuentre la solución para estos vectores de valores independientes  b

In [75]:
from src import descomposicion_LU, resolver_LU

$$b1=
\begin{bmatrix}
1\\
2 \\
4
\end{bmatrix}
$$

In [76]:
L1, U1 = descomposicion_LU(np.array(A1))
b1 = np.array([1,2,4])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x1)

[01-13 19:31:17][INFO] 
[[  1.   3.   4.]
 [  0.  -5.  -5.]
 [  0. -10. -15.]]
[01-13 19:31:17][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 19:31:17][INFO] 
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
[01-13 19:31:17][INFO] Sustitución hacia adelante
[01-13 19:31:17][INFO] y = 
[[1.]
 [0.]
 [0.]]
[01-13 19:31:17][INFO] Sustitución hacia atrás
[01-13 19:31:17][INFO] i = 1
[01-13 19:31:17][INFO] suma = [0.]
[01-13 19:31:17][INFO] U[i, i] = -5.0
[01-13 19:31:17][INFO] y[i] = [0.]
[01-13 19:31:17][INFO] i = 0
[01-13 19:31:17][INFO] suma = [0.]
[01-13 19:31:17][INFO] U[i, i] = 1.0
[01-13 19:31:17][INFO] y[i] = [1.]
Matriz L:
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 2. 1.]]
Matriz U:
[[ 1.  3.  4.]
 [ 0. -5. -5.]
 [ 0.  0. -5.]]
Solución del sistema Ax=b:
[[ 1.]
 [-0.]
 [-0.]]


$$b2=
\begin{bmatrix}
3\\
-5 \\
2
\end{bmatrix}
$$

In [77]:
L2, U2 = descomposicion_LU(np.array(A2))
b2 = np.array([3,-5,2])
x2 = resolver_LU(L2, U2, b2)
print("Matriz L:")
print(L2)
print("Matriz U:")
print(U2)   
print("Solución del sistema Ax=b:")
print(x2)

[01-13 19:31:17][INFO] 
[[  1.   2.   3.]
 [  0.   1.   4.]
 [  0.  -4. -15.]]
[01-13 19:31:17][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 19:31:17][INFO] 
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
[01-13 19:31:17][INFO] Sustitución hacia adelante
[01-13 19:31:17][INFO] y = 
[[  3.]
 [ -5.]
 [-33.]]
[01-13 19:31:17][INFO] Sustitución hacia atrás
[01-13 19:31:17][INFO] i = 1
[01-13 19:31:17][INFO] suma = [-132.]
[01-13 19:31:17][INFO] U[i, i] = 1.0
[01-13 19:31:17][INFO] y[i] = [-5.]
[01-13 19:31:17][INFO] i = 0
[01-13 19:31:17][INFO] suma = [155.]
[01-13 19:31:17][INFO] U[i, i] = 1.0
[01-13 19:31:17][INFO] y[i] = [3.]
Matriz L:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 5. -4.  1.]]
Matriz U:
[[1. 2. 3.]
 [0. 1. 4.]
 [0. 0. 1.]]
Solución del sistema Ax=b:
[[-152.]
 [ 127.]
 [ -33.]]


$$b3=
\begin{bmatrix}
7\\
8 \\
-1
\end{bmatrix}
$$

In [78]:
L3, U3 = descomposicion_LU(np.array(A3))
b3 = np.array([7,8,-1])
x3 = resolver_LU(L3, U3, b3)
print("Matriz L:")
print(L3)
print("Matriz U:")
print(U3)   
print("Solución del sistema Ax=b:")
print(x3)

[01-13 19:31:17][INFO] 
[[4.   2.   1.  ]
 [0.   0.   2.5 ]
 [0.   2.5  3.75]]


ValueError: No existe solución única.

$$b1=
\begin{bmatrix}
1\\
2 \\
4 \\
5
\end{bmatrix}
$$

In [ ]:
L4, U4 = descomposicion_LU(np.array(A4))
b4 = np.array([1,2,4,5])
x4 = resolver_LU(L4, U4, b4)
print("Matriz L:")
print(L4)
print("Matriz U:")
print(U4)   
print("Solución del sistema Ax=b:")
print(x4)

[01-13 19:28:28][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 19:28:28][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 19:28:28][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:28:28][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:28:28][INFO] Sustitución hacia adelante
[01-13 19:28:28][INFO] y = 
[[  1.]
 [  0.]
 [  3.]
 [-10.]]
[01-13 19:28:28][INFO] Sustitución hacia atrás
[01-13 19:28:28][INFO] i = 2
[01-13 19:28:28][INFO] suma = [-1.11111111]
[01-13 19:28:28][INFO] U[i, i] = 5.0
[01-13 19:28:28][INFO] y[i] = [3.]
[01-13 19:28:28][INFO] i = 1
[01-13 19:28:28][INFO] suma = [3.13333333]
[01-13 19:28:28][INFO] U[i, i] = -1.0
[01-13 19:28:28][INFO] y[i] = [0.]
[01-13 19:28:28][INFO] i = 0
[01-13 19:28:28][INFO] suma = [16.35555556]
[01-13 19:28:28][INFO] U[i, i] = 2.0
[01-13 19:28:28][INFO] y[i] = [1.]
Mat

$$b2=
\begin{bmatrix}
3\\
-5 \\
2 \\
6
\end{bmatrix}
$$

In [ ]:
L5, U5 = descomposicion_LU(np.array(A4))
b5 = np.array([3,-5,2,6])
x5 = resolver_LU(L5, U5, b5)
print("Matriz L:")
print(L5)
print("Matriz U:")
print(U5)   
print("Solución del sistema Ax=b:")
print(x5)

[01-13 19:29:33][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 19:29:33][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 19:29:33][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:29:33][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:29:33][INFO] Sustitución hacia adelante
[01-13 19:29:33][INFO] y = 
[[  3.]
 [-11.]
 [-12.]
 [ 45.]]
[01-13 19:29:33][INFO] Sustitución hacia atrás
[01-13 19:29:33][INFO] i = 2
[01-13 19:29:33][INFO] suma = [5.]
[01-13 19:29:33][INFO] U[i, i] = 5.0
[01-13 19:29:33][INFO] y[i] = [-12.]
[01-13 19:29:33][INFO] i = 1
[01-13 19:29:33][INFO] suma = [-16.2]
[01-13 19:29:33][INFO] U[i, i] = -1.0
[01-13 19:29:33][INFO] y[i] = [-11.]
[01-13 19:29:33][INFO] i = 0
[01-13 19:29:33][INFO] suma = [-36.2]
[01-13 19:29:33][INFO] U[i, i] = 2.0
[01-13 19:29:33][INFO] y[i] = [3.]
Matriz L:
[[ 1.  0.

$$b1=
\begin{bmatrix}
7\\
8 \\
-1 \\
0
\end{bmatrix}
$$

In [ ]:
L5, U5 = descomposicion_LU(np.array(A4))
b5 = np.array([7,8,-1,0])
x5 = resolver_LU(L5, U5, b5)
print("Matriz L:")
print(L5)
print("Matriz U:")
print(U5)   
print("Solución del sistema Ax=b:")
print(x5)

[01-13 19:30:29][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  1. 12.  9.]
 [ 0.  0. 20. 13.]]
[01-13 19:30:29][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0. 20. 13.]]
[01-13 19:30:29][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:30:29][INFO] 
[[ 2.  4.  6.  1.]
 [ 0. -1. -7. -8.]
 [ 0.  0.  5.  1.]
 [ 0.  0.  0.  9.]]
[01-13 19:30:29][INFO] Sustitución hacia adelante
[01-13 19:30:29][INFO] y = 
[[  7.]
 [ -6.]
 [-14.]
 [ 35.]]
[01-13 19:30:29][INFO] Sustitución hacia atrás
[01-13 19:30:29][INFO] i = 2
[01-13 19:30:29][INFO] suma = [3.88888889]
[01-13 19:30:29][INFO] U[i, i] = 5.0
[01-13 19:30:29][INFO] y[i] = [-14.]
[01-13 19:30:29][INFO] i = 1
[01-13 19:30:29][INFO] suma = [-6.06666667]
[01-13 19:30:29][INFO] U[i, i] = -1.0
[01-13 19:30:29][INFO] y[i] = [-6.]
[01-13 19:30:29][INFO] i = 0
[01-13 19:30:29][INFO] suma = [-17.84444444]
[01-13 19:30:29][INFO] U[i, i] = 2.0
[01-13 19:30:29][INFO] y[i] = [7.]